sudo: required

services:
  - docker

before_install:
    - openssl aes-256-cbc -K $encrypted_898c097730ba_key -iv $encrypted_898c097730ba_iv -in sign-key.enc -out ./sign-key -d
    - docker pull pritunl/archlinux
    - sudo chown 1000:1000 -R ${PWD}
    - docker run --name eloquentos -itd -v ${PWD}:/mnt pritunl/archlinux /bin/bash
    - docker exec eloquentos /bin/sh -c "cd /mnt && ./travis.sh"
    - docker exec -u eloquentos eloquentos /bin/sh -c "pacman-key --add /mnt/sign-key"

script: docker exec -u eloquentos eloquentos /bin/sh -c "cd /mnt && ./build.sh"
