sudo: required

env:
    - secure: "C9qtg7UB416Uzzg7zzmyCjaGm5tSYnXPV1KmXpbhy4mFhvuKRl9J/WWKf+hor+oYmx2062Mw/Heya5C2hQBPPzSlFEsbjl7HWTv8gghfXaVzKF38o0hb9eUtdOpUDN8KmaSgLM1zslczDL/Qt7IyN/plfws+MOwKH8XZ+pgaftLfghcgCOjamy3K6lKQ64hmQ+kKh0l/RhG736LdXXkn4nqazhNEUB6d5HpPJSiLWZPiekIf4t6bldLeW1dmXl/amLEmeGX7qHdWBNoY/JAG0seDJPvcn2KBTi0xMC6vCIpGmWfQ1OTjRpsU9oa90Q2RzaCf6q0m3sJ2/duzc6/eG4vGWczepKhFB6tyCCtOgRd51uUbOQw32y4AavM3uYVNKwT2iIiViB4cnRU6dTy86xkaosqoducWC6okEJTALCZZeDTPNsBD3JUbcW16YIOIXTxqrZvVf9B3iuhqHVTMB7hPu9xuMVn7m+wkU6r5WKhiEib4I0/hzuAFoV8BR0lFPd0MNoPTRA7zBtLJBjxVVM2BNgaHQRDbI8HYn+H81O0D5Rw8XaGA22/rkYcP1FfFvb1+8LznNaaY8rpyCbsK0abqrWttNfr86OxPeChZuQ7fvDHirOJvBAVl83/cNQPU+VvPCrjyuLyaVXgEv9FUBz6jCbgBSC182ER7icxUI8Q="

services:
    - docker

before_install:
    - ls -la
    - openssl aes-256-cbc -K $encrypted_898c097730ba_key -iv $encrypted_898c097730ba_iv -in sign-key.enc -out sign-key -d
    - docker pull pritunl/archlinux
    - sudo chown 1000:1000 -R ${PWD}
    - docker run --name eloquentos -itd -v ${PWD}:/mnt pritunl/archlinux /bin/bash
    - docker exec eloquentos /bin/sh -c "cd /mnt && ./travis.sh"
    - docker exec -u eloquentos eloquentos /bin/sh -c "gpg --allow-secret-key-import --import /mnt/sign-key"

script: docker exec -u eloquentos eloquentos /bin/sh -c "cd /mnt && ./build.sh"

after_success:
    - sudo chown travis:travis -R ${PWD}
    - ls -la

before_deploy: git fetch --tags

after_success:
    - sudo apt-get install -y sshpass
    - ./deploy-testing.sh
